### ISSUE TITLE
feature - turn off logs

### ISSUE THREAD

**Issue by p-r-a-s-h-a-n-t** [bitwkit/resource-pools#1]
Hello bitwkit,

Would it be possible to disable logging by way of config option and only log if an error occurs?

Happy to create PR if you are happy to accept contributions.

Kind regards,
p-r-a-s-h-a-n-t

**Comment by bitwkit** [comment]
Hi p-r-a-s-h-a-n-t,
Yes, surely a useful feature. I'm OK with a PR if you're willing to contribute.

**Comment by bitwkit** [comment]
Added an optional 'log' function to config, which is supposed to take a log message level (severity) and the message, and to process them by itself. Logging to the console is replaced with calling this function, if present.
